include "/etc/bird/auto_assign.conf";

router id DN42_SELF_IP;

protocol device {
    scan time 10;
}

include "/etc/bird/dn42.conf";
include "/etc/bird/clearnet.conf";
include "/etc/bird/ibgp.conf";

protocol kernel Kernel {
    scan time 20;
    merge paths on;
    ipv4 {
        import none;
        export filter {
            if bgp_large_community ~ [(NET_AS, 300, NET_AS), (NET_AS, 6000, NET_AS)] || source = RTS_STATIC then reject;
            #if !INVALID_NET() then krt_prefsrc = NET_SELF_IP;
            if DN42_VALID_NET() then krt_prefsrc = DN42_SELF_IP;
            accept;
        };
    };
}

protocol kernel Kernelv6 {
    scan time 20;
    merge paths on;
    ipv6 {
        import none;
        #export all;
        export filter {
            if bgp_large_community ~ [(NET_AS, 300, NET_AS), (NET_AS, 6000, NET_AS)] || source = RTS_STATIC then reject;
            if !INVALID_NET() then krt_prefsrc = NET_SELF_IPv6;
            if DN42_VALID_NET() then krt_prefsrc = DN42_SELF_IPv6;
            accept;
        };
    };
}
