define DN42_PREFIXES_V4 = [
    172.20.0.0/14{21,29}, # dn42
    172.20.0.0/24{28,32}, # dn42 Anycast
    172.21.0.0/24{28,32}, # dn42 Anycast
    172.22.0.0/24{28,32}, # dn42 Anycast
    172.23.0.0/24{28,32}, # dn42 Anycast
    172.31.0.0/16+,       # ChaosVPN
    10.100.0.0/14+,       # ChaosVPN
    10.127.0.0/16{16,32}, # neonetwork
    10.0.0.0/8{15,24}     # Freifunk.net
];

define DN42_PREFIXES_V6 = [
    fd00::/8{44,64}       # ULA address space as per RFC 4193
];

function DN42_VALID_NET() {
  case net.type {
      NET_IP4: return net ~ DN42_PREFIXES_V4;
      NET_IP6: return net ~ DN42_PREFIXES_V6;
  }
}

roa4 table dn42_roa;
roa6 table dn42_roa_v6;

protocol static DN42_ROA {
    roa4 { table dn42_roa; };
    include "/etc/bird/dn42/roa_dn42.conf";
}

protocol static DN42_ROAv6 {
    roa6 { table dn42_roa_v6; };
    include "/etc/bird/dn42/roa_dn42_v6.conf";
}

filter DN42_CUSTOMER_IMPORT_FILTER {
  if DN42_VALID_NET() && !DN42_SELF_NET_CHECK() && bgp_path.len < 10 then {
    if (roa_check(dn42_roa, net, bgp_path.last) != ROA_VALID) then {
      print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
      reject;
    } else accept;
  } else reject;
}

filter DN42_CUSTOMER_EXPORT_FILTER {
  bgp_path.delete([4209250000..4209259999]);
  if DN42_VALID_NET() && source ~ [RTS_STATIC, RTS_BGP] && bgp_large_community !~ [(NET_AS, 6000, NET_AS)] then accept; else reject;
}

template bgp DN42_CUSTOMER {
    local as DN42_AS;
    enable extended messages;

    ipv4 {
        import filter DN42_CUSTOMER_IMPORT_FILTER;
        export filter DN42_CUSTOMER_EXPORT_FILTER;
        import limit 800 action block;
        export limit 800 action block;
        extended next hop;
    };

    ipv6 {
        import filter DN42_CUSTOMER_IMPORT_FILTER;
        export filter DN42_CUSTOMER_EXPORT_FILTER;
        import limit 800 action block;
        export limit 800 action block;
    };
}

#include "/etc/bird/dn42/community_filters.conf";
include "/etc/bird/dn42/peers/*.conf";
