filter IBGP_IMPORT_FILTER {
    bgp_large_community.add((NET_AS, 6000, NET_AS));
    bgp_local_pref = 300;
    accept;
}

filter IBGP_EXPORT_FILTER {
    if bgp_large_community ~ [(NET_AS, 300, NET_AS)] || source = RTS_STATIC then reject;
    if !INVALID_NET() then accept;
    if DN42_VALID_NET() then accept;
    reject;
}

protocol direct IBGP_DUMMY {
    interface "dummy0";

    ipv4 {
      import filter IBGP_IMPORT_FILTER;
    };

    ipv6 {
      import filter IBGP_IMPORT_FILTER;
    };
}

template bgp IBGP_PEER {
    local as PRIV_AS;
    confederation 42925;
    confederation member yes;
    multihop 2;
    enable extended messages;

    ipv4 {
        import all;
        export filter IBGP_EXPORT_FILTER;
        extended next hop;
        next hop self;
    };

    ipv6 {
        import all;
        export filter IBGP_EXPORT_FILTER;
        next hop self;
    };
}

include "/etc/bird/ibgp/peers/*.conf";
